<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    ' has error: ' => '',
    ': password reset' => '',
    'Accept' => '',
    'Account' => '',
    'Account ID' => '',
    'Account Points' => '',
    'Account history' => '',
    'Account: {points} points' => '',
    'Amount' => '',
    'Amount Change' => '',
    'Amount: {amount}' => '',
    'Amount: {points} points' => '',
    'Another one' => '',
    'Can\'t get settings from database!' => '',
    'Click {link} to reset your password' => '',
    'Created At' => '',
    'Data' => '',
    'Data array must contain amount key!' => '',
    'Date: ' => '',
    'Description' => '',
    'Direction' => '',
    'Email' => '',
    'Fill form below and we\'ll ship your prize soon' => '',
    'Fill the form below to get the prize' => '',
    'Forgot password?' => '',
    'Get the prize' => '',
    'ID' => '',
    'Lucky moment!' => '',
    'Message Template' => '',
    'Mighty kind' => '',
    'Money' => '',
    'Password' => '',
    'Password recovery' => '',
    'Password reset' => '',
    'Password reset link was sent to your email.' => '',
    'Password reset token cannot be blank.' => '',
    'Password was successfully reset.' => '',
    'Play' => '',
    'Please check it and follow provided link to reset your password.' => '',
    'Please fill out the following fields to get password recovery link:' => '',
    'Please fill out the following fields to reset your password:' => '',
    'Please fill out the following fields to sign up:' => '',
    'Prize (id: {prizeId}) added successfully' => '',
    'Prize ID' => '',
    'Prize data' => '',
    'Prize not found!' => '',
    'Remember me' => '',
    'Repeat password' => '',
    'See your account history here soon' => '',
    'Sent At' => '',
    'Sign In' => '',
    'Sign Up' => '',
    'Sign in' => '',
    'Sign up' => '',
    'Status' => '',
    'Submit' => '',
    'There are no prizes left ,comeback later!' => '',
    'There is no user with this email address.' => '',
    'Title' => '',
    'To bank' => '',
    'To points' => '',
    'Type' => '',
    'User ID' => '',
    'User {username} (#{userid}) has won a prize!' => '',
    'Username' => '',
    'We are sorry, no prizes left!' => '',
    'Wrong password' => '',
    'Wrong password reset token.' => '',
    'You already got your prize!' => '',
    'You can choose transfer amount to your bank account or to account points' => '',
    'You can transfer prize amount account' => '',
    'You have to sign in before start winning.' => '',
    'You haven\'t won a prize yet!' => '',
    'You won!' => '',
    'Your account was successfully funded by: {points} points' => '',
    'Your bank account will be funded by: {currency} soon' => '',
    'Your prize is {prizeTitle}!' => '',
    'item' => '',
    'money' => '',
    'points' => '',
];
